# Generated by Django 3.2.1 on 2023-10-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodMorning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_hour', models.IntegerField(blank=True, null=True)),
                ('am_pm', models.CharField(choices=[('am', 'AM'), ('pm', 'PM')], max_length=10)),
            ],
        ),
    ]
